services:
    app:
        container_name: linuxbox
        image: ghcr.io/mcbtaguiad/linuxbox-centos9:main
        build:
            context: .
            dockerfile: Dockerfile
        # entrypoint: tail -f /dev/null
        restart: always
        ports:
            - "2222:22"
