apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-deployment
  namespace: linuxbox
rules:
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["get", "patch", "list", "watch"]